name: CD Power BI - Déploiement automatique

on:
  release:
    types: [published]  # Déclenché quand tu publies une nouvelle release (ex: v2.1.0)

jobs:
  deploy-to-powerbi:
    runs-on: windows-latest
    name: Déployer sur Power BI Service

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Installer les modules Power BI (PowerShell)
      run: |
        Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
        Install-Module -Name MicrosoftPowerBIMgmt.Reports -Force -Scope CurrentUser
        Install-Module -Name MicrosoftPowerBIMgmt.Workspaces -Force -Scope CurrentUser

    - name: Authentifier sur Power BI Service (Service Principal)
      run: |
        $clientId = "${{ secrets.PBI_CLIENT_ID }}"
        $clientSecret = "${{ secrets.PBI_CLIENT_SECRET }}"
        $tenantId = "${{ secrets.PBI_TENANT_ID }}"

        Write-Host "Connexion au Power BI Service..."
        $SecureSecret = ConvertTo-SecureString $clientSecret -AsPlainText -Force
        $Credential = New-Object System.Management.Automation.PSCredential($clientId, $SecureSecret)
        Connect-PowerBIServiceAccount -ServicePrincipal -Credential $Credential -Tenant $tenantId
        Write-Host "✅ Connexion réussie à Power BI Service !"

    - name: Déployer le rapport Power BI
      run: |
        $workspaceId = "${{ secrets.PBI_WORKSPACE_ID }}"
        $reportPath = "CI CD.pbix"
        Write-Host "Déploiement du rapport $reportPath vers Power BI Service..."
        Import-PowerBIReport -Path $reportPath -WorkspaceId $workspaceId -Name "CI CD" -ConflictAction Overwrite
        Write-Host "✅ Déploiement terminé avec succès !"
