name: CD Power BI - Déploiement automatique

on:
  release:
    types: [published]

jobs:
  deploy-to-powerbi:
    runs-on: windows-latest
    name: Déployer sur Power BI Service

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Installer les modules Power BI
      shell: pwsh
      run: |
        Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
        Install-Module -Name MicrosoftPowerBIMgmt.Reports -Force -Scope CurrentUser
        Install-Module -Name MicrosoftPowerBIMgmt.Workspaces -Force -Scope CurrentUser

    - name: Authentifier et déployer vers Power BI Service (via API REST)
      shell: pwsh
      run: |
        $clientId = "${{ secrets.PBI_CLIENT_ID }}"
        $clientSecret = "${{ secrets.PBI_CLIENT_SECRET }}"
        $tenantId = "${{ secrets.PBI_TENANT_ID }}"
        $workspaceId = "${{ secrets.PBI_WORKSPACE_ID }}"
        $reportPath = "CI CD.pbix"

        Write-Host "🔐 Récupération du token Azure AD..."
        $body = @{
            grant_type    = "client_credentials"
            client_id     = $clientId
            client_secret = $clientSecret
            scope         = "https://analysis.windows.net/powerbi/api/.default"
        }
        $response = Invoke-RestMethod -Method Post -Uri "https://login.microsoftonline.com/$tenantId/oauth2/v2.0/token" -Body $body
        $token = $response.access_token
        Write-Host "✅ Token obtenu avec succès !"

        Write-Host "🚀 Déploiement du rapport $reportPath vers Power BI Service..."
        $headers = @{
          "Authorization" = "Bearer $token"
        }

        $uri = "https://api.powerbi.com/v1.0/myorg/groups/$workspaceId/imports?datasetDisplayName=CI%20CD&nameConflict=Overwrite"
        $form = @{
          "file" = Get-Item $reportPath
        }

        # Envoi du rapport PBIX via API REST
        Invoke-RestMethod -Uri $uri -Headers $headers -Method Post -InFile $reportPath -ContentType "application/octet-stream"

        Write-Host "✅ Déploiement terminé avec succès sur Power BI Service."
