name: CD Power BI - Déploiement automatique

on:
  release:
    types: [published]  # Se déclenche automatiquement à chaque nouvelle release (ex: v1.0.0)

jobs:
  deploy-to-powerbi:
    runs-on: windows-latest
    name: Déployer sur Power BI Service

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Installer les modules Power BI (PowerShell)
      shell: pwsh
      run: |
        Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
        Install-Module -Name MicrosoftPowerBIMgmt.Reports -Force -Scope CurrentUser
        Install-Module -Name MicrosoftPowerBIMgmt.Workspaces -Force -Scope CurrentUser

    - name: Authentifier sur Power BI Service (Service Principal)
      shell: pwsh
      run: |
        $appId = "${{ secrets.PBI_CLIENT_ID }}"
        $clientSecret = "${{ secrets.PBI_CLIENT_SECRET }}"
        $tenantId = "${{ secrets.PBI_TENANT_ID }}"

        Write-Host "Connexion à Power BI Service avec Service Principal..."
        $secureSecret = ConvertTo-SecureString $clientSecret -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($appId, $secureSecret)

        Connect-PowerBIServiceAccount -ServicePrincipal -Tenant $tenantId -ApplicationId $appId -Credential $credential
        Write-Host "✅ Authentification réussie !"

    - name: Déployer le rapport Power BI
      shell: pwsh
      run: |
        $workspaceId = "${{ secrets.PBI_WORKSPACE_ID }}"
        $reportPath = "CI CD.pbix"

        Write-Host "🚀 Déploiement du rapport $reportPath vers Power BI Service..."
        Import-Module MicrosoftPowerBIMgmt.Reports -ErrorAction Stop
        Import-Module MicrosoftPowerBIMgmt.Workspaces -ErrorAction Stop

        Import-PowerBIReport -Path $reportPath -WorkspaceId $workspaceId -Name "CI CD" -ConflictAction Overwrite

        Write-Host "✅ Déploiement terminé avec succès !"
