name: CD Power BI - Déploiement automatique

on:
  release:
    types: [published]   # Déclenchement quand tu publies une release/tag (ex : v1.0.0)

jobs:
  deploy-to-powerbi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Afficher le contenu pour debug
        run: ls -la

      - name: Installer Power BI CLI (pbicli)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install powerbicli

      - name: Authentifier à Power BI Service
        env:
          PBI_TENANT_ID: ${{ secrets.PBI_TENANT_ID }}
          PBI_CLIENT_ID: ${{ secrets.PBI_CLIENT_ID }}
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
        run: |
          echo "Connexion à Power BI Service..."
          pbicli login \
            --service-principal \
            --tenant $PBI_TENANT_ID \
            --client-id $PBI_CLIENT_ID \
            --client-secret $PBI_CLIENT_SECRET

      - name: Déployer le rapport Power BI
        run: |
          echo "Publication du rapport sur Power BI Service..."
          pbicli import report \
            --workspace "Ikram workspace Dev" \
            --name "CI_CD_PowerBI_Report" \
            --path "CI CD.pbix" \
            --overwrite
